### ISSUE TITLE
DediConnect QoL

### ISSUE THREAD

**Issue by mvaessen** [gameserverapp/Platform#509]
## Onboarding improvements
- [x] Pre-install check for responsive FTP (21) port -> block install

## other
- [x] Kill game server (game server settings control btn)
- [x] Activate / disable mod for variable replace (#389)
- [x] Install mod when game server is running
- [x] Schedule mod removal when game server is running

## General
- [x] Add table view to machine overview (#439)
- [x] Add table view to machine services page (show)
- [x] show stats on machine block
- [x] show stats on table view
- [x] show stats on sidebar (machine settings)
- [x] show stats on "install game server" page per machine (#501)

### Machine stats
- [x] Separate endpoint for ajax calls
- [x] CPU load
- [x] Mem usage
- [x] Disk usage (#330)

## Uptime monitoring
- [x] Increase check frequency
- [x] send email to customer when machine is unavailable
- [x] send email to customer when machine is healthy again

## Image & game management
- [x] List of installed games
- [x] Option to purge individual installed games & docker images, to force complete redownload

## Docs
- [x] Setup DediConnect
- [x] Machine
- [x] Game server danger zone

## Game server
- [x] Select install location for game server (#173)
- [x] RconConnect validate script refactor

## Email notifications
- [x] Check all emails and review / update

## Other
- [x] Demo server
- [x] Add new DediConnect stuff to promo
