### ISSUE TITLE
Task QoL

### ISSUE THREAD

**Issue by mvaessen** [gameserverapp/Platform#517]
Actions
- [x] Add support for offline game server state for backup actions
- [x] Post discord json to channel (update existing or create new) action
- [x] Wipe tokens (#287)
- [x] Mute player (#271)
- [x] Ban player
- [x] Shop pack control
- [x] Supporter tier control
- [x] Expand `Conditional` action: check for day of week (#532)
- [x] Allow sending negative token amount via SendTokenAction
- [x] Consolidate game server related actions into 1 "Game server control" action
- [x] Move model-related actions (task, shop pack etc) under "Manage entities" category
- [x] Reload page with input on changing event or isGlobal (filterActions)
- [x] allow filter on `report type` for report trigger tasks
- [x] Change map (#436)
- [x] Change / generate seed 
- [x] loop over online players
- [x] loop over active game servers

Variables
- [x] Remaining role time

Events
- [x] Scheduled monthly at day of week (#261)
- [x] Every day at [hour] [minute] (#226)
- [x] webhook triggered

Achievement
- [x] Playtime session above X
- [x] Account was connected (any account, or specific type) (#656)

Performance
- [x] Load management (per dashboard rate limits, based on add-on)
- [x] Improved action compatibility feedback on gui based on a trigger, achievement or scheduled type selection
- [x] Send tokens action replace with Send tokens to player action
- [x] Delayed action exploit fix by requiring minimum 3 minute delay time
- [x] "Too many concurrent deliveries" - could also be telltale for inefficient task logic (add to docs + link)
- [x] update free tier: 2 actions p/delivery - 1 concurrent deliveries
- [x] Update paid standard: 5 actions per/delivery - 2 concurrent
- [x] Add concurrency limits per upgrade

Other
- [x] Add delay between actions (#292)

https://discord.com/channels/315049169071112193/424240875732860929/1158470027129933916
